package model.basket;

public enum BasketEvent {
    ADDED_ARTICLE,
    REMOVED_ARTICLE,
    REMOVED_ARTICLE_INDEX,
    REMOVED_ARTICLES,
    REMOVED_ARTICLE_INDICES,
    CLEARED_ARTICLES,
    TOTAL_PRICE_CHANGED
}
