package model.properties;

public enum Property {
    // Discounts
    DISCOUNT_EXPENSIVE,
    DISCOUNT_EXPENSIVE_AMOUNT,
    DISCOUNT_GROUP,
    DISCOUNT_GROUP_NUMBER,
    DISCOUNT_GROUP_AMOUNT,
    DISCOUNT_THRESHOLD,
    DISCOUNT_THRESHOLD_THRESHOLD,
    DISCOUNT_THRESHOLD_AMOUNT
}
